# Generated by Django 4.0.6 on 2022-07-10 22:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon', '0002_copypokemon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pokemonteam',
            name='pokemon_1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='first', to='pokemon.copypokemon'),
        ),
        migrations.AlterField(
            model_name='pokemonteam',
            name='pokemon_2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='second', to='pokemon.copypokemon'),
        ),
        migrations.AlterField(
            model_name='pokemonteam',
            name='pokemon_3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='third', to='pokemon.copypokemon'),
        ),
        migrations.AlterField(
            model_name='pokemonteam',
            name='pokemon_4',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fourth', to='pokemon.copypokemon'),
        ),
        migrations.AlterField(
            model_name='pokemonteam',
            name='pokemon_5',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fifth', to='pokemon.copypokemon'),
        ),
        migrations.AlterField(
            model_name='pokemonteam',
            name='pokemon_6',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sixth', to='pokemon.copypokemon'),
        ),
    ]
